stefan-hoeck/idris2-pack

- src/Pack/Runner/Install.idr
Also don't clean `support` files. `rm -r build/ttc` can in some cases be more reliable than `idris2 --clean` (if a module has been deleted for example) but this shouldn't matter
> Disable incremental compilation of idris2 compiler

- install.bash
On macos, `basename` needs `-s` instead of `--suffix`.  The short switch appears to work on Linux as well.  The sed expressions need a semicolon between the `p` and the `}`.  And on M1 with homebrew, we need to export `CPATH=/opt/homebrew/include` if that directory exists.
> Changes to install.bash for macos compatibility

- src/Pack/Admin/Report/Types.idr
Could make it stlightly easier to track down exactly what is included in package set. This link format might be specific to Github, though it looks like Gitlab also supports `\{url}/commit/\{sha}`. Not sure about other source code hosting, but the data constructor is named RGithub after all.
> Add links to commits to status

- .github/workflows/docker-build.yml
Can maybe change this in future to publish something on main, and build
the `nightly-*` tags on the schedule, but this should be good enough for
now.
> Only publish docker image on schedule

- src/Pack/Config/Env.idr
- src/Pack/Config/TOML.idr
- src/Pack/Config/Types.idr
- src/Pack/Database/TOML.idr
- src/Pack/Database/Types.idr
This implements #96  . It is now possible to add a `latest` meta commit to custom packages in the `pack.toml` files. Pack will then resolve the package by fetching the latest commit from the given branch. Packages will be (re)installed as needed. Here's the syntax to use:
```toml
[custom.all.rio]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-rio"
commit = "latest:sys"
ipkg   = "rio.ipkg"
```
> [ new ] support meta commits

- install.bash
The installation script did not create the required symlink to the `idris2` binary. This also adds some notes to the script.
> [ fix ] idris symlink

- src/Pack/CmdLn/Completion.idr
- src/Pack/CmdLn/Opts.idr
- src/Pack/Config/Env.idr
- src/Pack/Runner.idr
This allows us to use `pack switch latest`, which will then update the data collections, select the latest nightly and install all auto-libs and apps, rewire the `bin` symlink, and adjust the `collection` entry in the global `pack.toml` in one fell swoop. Highly useful for people living on the bleeding edge.
> [ new ] support switching to latest collection

- src/Pack/Core/Types.idr
- src/Pack/Runner/Develop.idr
> [ fix ] use relative .idr paths in presence of .ipkg

- src/Pack/Admin/Runner.idr
- src/Pack/CmdLn/Opts.idr
- src/Pack/CmdLn/Types.idr
- src/Pack/Config/Environment.idr
- src/Pack/Core/Git.idr
- src/Pack/Core/Types.idr
- src/Pack/Database/Types.idr
- src/Pack/Runner.idr
This is an additional enhancement to #96 , which will cache the latest fetched commit hash, and will only re-fetch commit hashes when invoking `pack fetch`. This will drastically speed up pack's startup time in the presence of custom GitHub packages annotated with `commit = "latest:branch"`. Use `commit = "fetch-latest:branch"` in order to always fetch the latest commit hash when starting pack.
> [ performance ] less commit fetching

- .github/workflows/docker-build.yml
Looks like this is failing:
https://github.com/stefan-hoeck/idris2-pack/runs/7777579571?check_suite_focus=true
Also, the action doesn't seem maintained anymore:
https://github.com/satackey/action-docker-layer-caching
Some future work could be to migrate to the official docker build-push-action:
https://github.com/docker/build-push-action
That has some better caching behaviour:
https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
> Remove docker cache

- src/Pack/Runner.idr
This might be related to #152  . At the very least it is annoying that pack starts using the package collection we are switching to before the switch is completed.
> [ fix ] update global pack.toml after switch is completed

- README.md
User experience story: I decided to try `pack` (and this is great tool, I must say), I read readme and the first thing I decided to install was `lsp`. But immediately I got a prompt asking something not familiar to me -- something about custom build hooks. That was disappointing.
I think mentioning of them worth to be in the readme. At least this prompt would not be a complete surprise. I suggest some wording for this.
> [ doc ] Add a note on possibility of custom build hooks prompt

- README.md
I think this is much more convenient and intuitive ;-)
> [ ux ] Make collection's badge in the readme go to the status page

- src/Pack/Runner/Install.idr
Please, forgive me if it was intended, but I think, the current look with "package collection" on another line looks weird, especially near with the rest of output which takes much longer than this particular line. WDYT?
I also want to suggest general treatment of newlines in log messages to make all look (subjectively?) better.
> [ minor, ux ] Make info message to be one line

- pack.ipkg
I've found it when was playing with cleaning. By the way, I found out that `pack-admin.ipkg` and `micropack.ipkg` do not have modules list at all, thus for these packages only their main module is cleaned.
> [ minor, fix ] Add forgotten module to the `pack.ipkg`

- src/Pack/Config/Environment.idr
Manages the case when string of the log message contains newlines. I personally think that when the whole log message is indented uniformly, this reads better.
Notice that this PR changes a bit present behaviour, especially of `logMany`. Previously, say, "installing libraries" message was looking like this:
```
...
[ info ] Installing libraries:
toml
filepath
[ info ] Installing library (with sources): toml
...
```
This change makes this look like this:
```
...
[ info ] Installing libraries:
toml
filepath
[ info ] Installing library (with sources): toml
...
```
One more change is that `log` for an empty string now does nothing and before is would print the log prefix. I can revert this behaviour, but I thought that if `logMany` does nothing if it has non-empty message and empty list of …
> [ logging ] Print all lines of the log message indented

- src/Pack/CmdLn/Completion.idr
- src/Pack/CmdLn/Opts.idr
- src/Pack/Core/Types.idr
Basically, remove code duplication, mainly from help and error messages. This change is split to two commits to ease review, since the second commit it purely technical.
UPD: Oh, I forgot to say, that this PR slightly changes help and error messages: in help message `"and"` is replaced with `", "` for simplicity, and error message for wrong log level was changed to contain `"- "` before each alternative.
> [ refactor ] Make log levels list to have a single source of truth

- src/Pack/Runner/Develop.idr
#179 introduced a regression when running `pack repl` without an additional source file argument. This fixes it.
> [ fix ] pack repl without source file

- src/Pack/CmdLn/Opts.idr
- src/Pack/Config/TOML.idr
- src/Pack/Config/Types.idr
- src/Pack/Runner/Develop.idr
Closes #189.
Well, as I said in the original issue, I've implemented a solution where existing `repl.rlwrap` option can be not only a boolean, but take also a string or array of strings with additional arguments.
But only after implementation I thought that *maybe* having a separate option would be good for the case when `--rlwrap` option is given. It could turn on usage of `rlwrap` itself, while taking additional arguments from the `pack.toml`. However, I personally, don't feel this case realistic, since I think either one uses `rlwrap` (and maybe tunes it), or just does not use. What do you think?
For now, `--rlwrap` CLI option takes an optional string with additional arguments, just in case.
> [ new ] Support for passing additional arguments to `rlwrap`

- src/Pack/Admin/Runner.idr
- src/Pack/CmdLn/Completion.idr
- src/Pack/CmdLn/Opts.idr
- src/Pack/CmdLn/Types.idr
- src/Pack/Config/Environment.idr
- src/Pack/Config/Types.idr
- src/Pack/Core/Types.idr
- src/Pack/Runner.idr
- src/Pack/Runner/Database.idr
- src/Pack/Runner/Develop.idr
- src/Pack/Runner/Install.idr
The goal of this PR is to give clearer error messages in case of invalid command arguments as well as to provide detailed per-command descriptions via `pack help <cmd>` instead of listing all commands plus their description with `pack help`. In addition, the way we parse commands and their arguments has been completely overhauled.
Once this is ready, it should fix #165 and supersed #143, which seems to have stalled.
Note: This PR does *not* change the order in which pack parses command-line options and commands, so this is unrelated to #134.
> [ refactor ] command help and clearer errors

- src/Pack/Runner/Database.idr
This is a follow-up on #196 , fixing an invisible prompt and waiting `getLine` call in case no directories need to be removed.
> [ fix ] dont prompt when there is nothing to clean

- src/Pack/Runner/Develop.idr
- src/Pack/Runner/Install.idr
This is a potential fix for #167, although I haven't tested it in earnest yet. This might be made superfluous by idris-lang/Idris2#2684 in which case I'll just delete it.
> [ new ] delete build dir if outdated

- src/Pack/Config/Types.idr
- src/Pack/Runner.idr
This, besides all, removed a "special value" (empty string) hack of `argDesc_`, and simplifies a function implementation, that traverses list of commands.
> [ cleanup ] Replace hacky way of current dir passing to direct one

- src/Pack/Config/Types.idr
Or else, it gives strange error: write `app`, it says "wrong, use `lib` or `app`".
> [ minor, fix ] Fix a hint of the CLI help for package kind

- src/Pack/Admin/Runner.idr
The pack-db CI is rather quiet at the moment. This changes it.
> [ log ] set log-level to Build when checking DB

- src/Pack/Admin/Report/Types.idr
- src/Pack/Admin/Runner/Check.idr
- src/Pack/CmdLn/Completion.idr
- src/Pack/CmdLn/Types.idr
- src/Pack/Config/Environment.idr
- src/Pack/Database/TOML.idr
- src/Pack/Database/Types.idr
- src/Pack/Runner.idr
- src/Pack/Runner/Database.idr
- src/Pack/Runner/Develop.idr
- src/Pack/Runner/Install.idr
- src/Pack/Runner/Query.idr
With this PR, a new `test` field is added to package descriptions pointing to a single `.ipkg` file used for running tests via `pack test [pkg] [args]`. At the moment, I keep this very basic: Only a single test suite is supported, but this may be  relaxed in the future. In addition, while it is possible to pass command-line arguments to the test suite, it is assumed that the app also runs without arguments when running `pack-admin check-db`.
Note: It is already easily possible to specify local packages in local `pack.toml` files, which can then serve as test runners. With this new command, it is now also possible to run test suites automatically when building the nightly package collections. In addition, it makes the default case of a single Idris test suite a bit less cumbersome to …
> [ new ] Add command for running test suites

- README.md
- src/Pack/Runner/New.idr
The `new` command now also creates a skeleton test suite for the new library plus a local `pack.toml` file listing the two new local packages.
> [ new ] create pack.toml and skeleton tests with new command

- src/Pack/Admin/Report/Types.idr
- src/Pack/Admin/Runner.idr
- src/Pack/Admin/Runner/Check.idr
The CI of pack-db and pack-docs are buggy and need an overhaul. The first step is to turn off docs and make test-success optional to at least get the nightly collections to build again.
> [ pack-admin ] check-db does not build docks

- src/Pack/CmdLn/Opts.idr
- src/Pack/Config/TOML.idr
- src/Pack/Config/Types.idr
- src/Pack/Core/TOML.idr
- src/Pack/Runner.idr
A short discussion on discord showed that pack users have different preferences about what log level to use as a default for different commands. This PR adds support for specifying the default log level for each command in the `pack.toml` file. In addition, the default log level for the `test` command is changed to `Warning` to be consistent with the default levels of `run` and `exec`.
The following syntax is supported:
```toml
[log]
exec = "build"
test  = "warning"
```
> [ config ] specify default log levels in pack.toml

- src/Pack/Runner/Install.idr
This fixes the same issue as #225 but for generating api docs: We need to remove those libraries from the cache of resolved libs, which we installed or for which we built api-docs during collection checking with `pack-admin`, otherwise, those libs get recompiled again and again when they are used as dependencies by other packages. This PR fixes this for docs generation.
> [ admin ] uncache library after creating docs

- src/Pack/CmdLn/Types.idr
Currently pack's CLI help options say this is what it should be
`pack help query`:
>  * `module` : Search a package by its modules. For
instance, `pack query module Data.List` will list all packages,
which export module `Data.List`. Only exact matches will
be listed.
Additionally this name makes more sense to me, as pack only queries for a single string
This is a breaking change, although `pack query` is generally used manually, so changing it shouldn't be a problem.
> Rename the `pack query modules` option to `pack query module`

- pack.ipkg
- src/Pack/Admin/Report/Types.idr
- src/Pack/CmdLn/Completion.idr
- src/Pack/CmdLn/Opts.idr
- src/Pack/Config/Types.idr
- src/Pack/Database/Tree.idr
- src/Pack/Database/Types.idr
- src/Pack/Runner/Develop.idr
- src/Pack/Runner/Query.idr
Adds query options `-tree` and `--parent-tree`. The former prints the dependency graph of a library, the latter the inverse dependency graph: A tree of libraries (transitively) depending on the one we are searching.
Examples:
```sh
» build/exec/pack --tree query rhone
rhone
|
|
quantifiers-extra
rhone-js
|______________________________
|            |                 |
dom          refined           rhone
|__          |_______          |
|  |         |       |         |
js elab-util algebra elab-util quantifiers-extra
|_________________
|                 |
quantifiers-extra elab-util
```
> [ new ] pretty-printed dependency graphs

- README.md
- src/Pack/CmdLn/Types.idr
This is following the merge of pull request #213 which creates a skeleton test suite and a `pack.toml` file and to be in line with the wish to have commands documented in the README file.
As it is a basic command, my belief is that it would be helpful for new users to have it documented in the README (although you could argue that the function is already pretty well documented with the `pack help` command and I would agree!).
> Update documentation of the `new` command and add an example in the README

- example1/README.md
- src/Pack/Config/Environment.idr
- src/Pack/Config/TOML.idr
- src/Pack/Config/Types.idr
- src/Pack/Runner/Database.idr
If we have local `pack.toml`s with alternative Idris commits set, currently `pack gc` will clean up all but only those in the localmost `pack.toml`, including the version from the current pack collection. This commit fixes it, `pack gc` now does not clean up an Idris commit mentioned in the current pack collection and in all local `pack.toml`s all way up. It fixes #246.
NB: if alternative Idris commit is not set in any local `pack.toml`s, the behaviour of `pack gc` should not change.
Additonally, this PR has a small commit with changes not worth a separate PR.
> [ gc ] Make `gc` command to not to clean up too much

- INSTALL.md
The official Chez Scheme now supports M1 macs, but we need to build from source until it is released.  This PR updates the documents to point at the upstream Chez and simplifies the build instructions.
> [ doc ] Update M1 mac instructions to point to upstream Chez

- install.bash
As mentioned on discord, in the `pack.toml` file copied from the installation bash script, the (commented-out) list of apps to be installed automatically still contains the old name of the `idris2-lsp` application. This is fixed with this PR.
> [ fix ] example apps list in install script

- src/Pack/Runner/Install.idr
Currently, the `lib` directories of installed libraries are not properly removed when deleting or re-installing libraries. This results in the new version of this directory being placed *inside* the already existing `lib` dir, so that for libraries with - for instance - C-bindings, the new C-bindings will not be found when developing such libraries locally.
The solution is trivial: Delete `pkgLibDir` when removing and before re-installing libraries.
> [ fix ] cleanup lib dir when removing or re-installing libs

- .editorconfig
- .github/workflows/ci-lib.yml
- .github/workflows/ci-super-linter.yml
- .github/workflows/docker-build.yml
- .github/workflows/notify-on-fail.yml
This is a technical stuff, originated by deprecation warnings shown by GitHub Actions and breaking changes in the upstream actions behaviour
EDIT: current problems are in liniting of the Dockerfile. Both problems are reasonable, but the first one maybe should be suppressed, since doing things properly will break everyone's usage of the pack's docker image for those who set `PACK_DIR` to `/root/.pack` manually.
EDIT2: ...but doing things properly will make transition from other's idris-containing images to the pack one seamless, without a need to reser the variable
EDIT3: maybe, we can make a proper user, and just add a symlink of `/root/.pack` to `/home/<pack-user>/.pack` for the seamless backwards compatibility. Also, setting `PACK_DIR` in the docker file seems to be a good idea, to not …
> [ bump ] Update deprecated CI actions and use newer linter version

- Dockerfile
`PACK_DIR` exposure is a backwards-compatible change since it anyway had to be set by the user with this particular value.
> [ lint ] Make Dockerfile pass the linter & expose `PACK_DIR` variable

- Dockerfile
I'm sorry, I didn't realise that in #276 I added a side-effecting call to `idris2` (which may change the state of `$HOME/.pack` in some circumstances), which made some operations failing in a flaky way when being run under the pack's docker image, e.g. when either two calls to `pack` are changing same files in a non-synchronised fashion, or another utilities, like `tar` are detecting changes in the file system, which are unexpected to them.
So, let's change the healthcheck command to a more appropriate one -- it checks that `pack` runs, but `help` command is not side-effecting.
> [ re #276 ] Make docker healthcheck to be not side-effecting

- INSTALL.md
As of Chez 10.0.0, Apple Silicon support is built-in to the official release. This has been confirmed to work ootb by dunham on the Idris2 Discord (thank you!), and so this PR updates the relevant parts of `INSTALL.md`.
> [ doc ] Update Apple Silicon note for Chez 10.0.0

- README.md
Seems this section is all implemented now, and as a reader it's unclear to me whether those things are still missing or were and have been completed
> Remove "Stuff still missing" section from README

- src/Pack/CmdLn/Types.idr
- src/Pack/Core/Types.idr
- src/Pack/Runner.idr
- src/Pack/Runner/Database.idr
- src/Pack/Runner/Develop.idr
I always lacked this (small) feature myself, but since I'm not the only one, I'd suppose to add it. Closes #297.
It is the most conservative solution: when no `ipkg` argument is given, it searches for the only available `ipkg` in the current directory and complains when was unable to find one or when there are too many of them.
It does **not** search in the upper directories when there is not `ipkg`s in the current one, and does not interact with any local `pack.toml` files during the search.
In case of additional arguments in the `run` command, since `Arg` parser for `Maybe` is greedy, we use this property to preserve the status quo behaviour: when anything is given after `pack run`, it is interpreted as the package name or package file. We are not trying to guess whether or not the …
> [ new ] Support searching the only `ipkg` when no package is given

- README.md
- install.bash
- src/Pack/CmdLn/Completion.idr
- src/Pack/CmdLn/Types.idr
- src/Pack/Runner.idr
- src/Pack/Runner/Uninstall.idr
This PR adds a new pack command `uninstall`, which can be invoked as follows:
```
$ pack uninstall
```
This pack command deletes the `$PACK_DIR`.
This PR closes #294.
> [ feature ] New Pack Command: Uninstall

- src/Pack/CmdLn/Opts.idr
- src/Pack/Config/Environment.idr
- src/Pack/Config/TOML.idr
- src/Pack/Config/Types.idr
- src/Pack/Runner/Develop.idr
PR #270 introduces `--extra-args` option enabling us to pass additional arguments to the compiler. But this options works in an unexpected way sometimes: e.g.
- it is fully ignored in commands like `build`, `cleanbuild` and, I think, `install`;
- extra args from local `pack.toml`s are stacked together, but only the last CLI option is taken into account.
What I propose is to pass extra-args to each call to the compiler (except for the very special internal calls of `pack` to the compiler using `idrisExec` function directly) so that any current and future command would respect this option. Also, I propose to take all passed extra arguments into account.
The only change that I made and I'm not certain about is the order: currently for the REPL options, where now `--extra-args` are used, …
> [ re #270 ] Make `extra-args` work more appropriately

- pack.toml
- src/Pack/Core/IO.idr
- src/Pack/Core/TOML.idr
- src/Pack/Core/Types.idr
This might just get a wee bit painful, but idris2-filepath added support for Windows paths, thus changing its public API. Let's see how this goes...
> [ compat ] adjust file paths to upstream changes

- src/Pack/Config/Environment.idr
It came up in a discussion  with @joelberkeley on discord that the homebrew `stdbuf` does not work in github `macos-latest` containers.  It fails complaining about an architecture mismatch:
```
dyld[2194]: tried: '/opt/homebrew/Cellar/coreutils/9.5/libexec/coreutils/libstdbuf.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/coreutils/9.5/libexec/coreutils/libstdbuf.so' (no such file), '/opt/homebrew/Cellar/coreutils/9.5/libexec/coreutils/libstdbuf.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e'))
```
This breaks pack in macos-latest containers if coreutils is installed.
This PR changes the code in pack that locates `stdbuf` to also verify that it successfully …
> [ fix ] don't use stdbuf if it is broken

- .github/workflows/docker-build.yml
- .gitignore
- Dockerfile
- Makefile
what is this PR? https://github.com/stefan-hoeck/idris2-pack/issues/317
> Build Docker images for Ubuntu 22.04 and 24.04

- src/Pack/Admin/Report/Types.idr
- src/Pack/Admin/Runner/Check.idr
- src/Pack/Config/Environment.idr
- src/Pack/Database/TOML.idr
- src/Pack/Database/Types.idr
- src/Pack/Runner/Database.idr
- src/Pack/Runner/Develop.idr
- src/Pack/Runner/Install.idr
- src/Pack/Runner/Query.idr
I'm putting this implementation up for discussion. I don't know  if the feature is desirable or if the name "notice" is the best choice.
The idea is that a package that was previously submitted to the `pack` collection might become defunct or have other important caveats worth telling users of the package about. For example, I want to move the `FVect` type from my `fvect` package into the `containers` package. I'm not deleting the `FVect` repository and there's no immediate need to remove it from the pack database -- removing it would potentially break downstream projects without warning. Instead, I would like to archive the GitHub repository and add a "notice" to the pack database entry that instructs consumers to find `FVect` in the `containers` package instead.
I especially don't know …
> Introduce package "notices"

- install.bash
- pack.toml
This also starts using the main branches of dependencies in the installation script instead of the commits listed in the DB.
> [ install ] install bytestring dependency in installation script
